name: null
channels:
 - conda-forge
 - defaults

dependencies:
 - python=3.9
 - jupyterlab=3.5.0 
 - numpy=1.23.4
 - scipy=1.9.3
 - pandas=1.5.1
 - xarray=2022.10.0
 - matplotlib=3.6.1
 - cartopy=0.21.0
 - fiona=1.8.22
